### ISSUE TITLE
Add 'Edit' functionality so users can edit Enum events after creation

### ISSUE THREAD

**Issue by phjlljp** [bitcoin-s/krystal-bull#59] opened 2021-05-13 09:18 UTC
Add 'Edit' functionality so users can edit Enum events after creation. I would like to be able to edit the title, and the enum events after creation, but before broadcast to the Oracle Explorer

**Comment by Christewart** [comment] 2021-05-13 11:00
> Add 'Edit' functionality so users can edit Enum events after creation. I would like to be able to edit the title, and the enum events after creation, but before broadcast to the Oracle Explorer

This is interesting and something we have to be careful of. 

As you intuit, we don't want to be modifying events after they have be shared externally. However there isn't any harm in doing this before you share an event with the wider world. 

I guess the crux of the issue is that we cannot determine when you have shared an event externally. We can track the oracle explorer stuff (if you do it with our API!) but we have no way of knowing i you copy and pasted the event and shared with a friend.

**Comment by benthecarman** [comment] 2021-05-13 15:04
Yeah, we can't really add an edit button as the oracle is cryptographically committing to what they enter the first time, if you really need to, you can just recreate a new event.

**Comment by phjlljp** [comment] 2021-05-16 23:19
My understanding was that the oracle is not cryptographically committed until it is broadcast to the oracle explorer. I was hoping to be able to edit the oracle within the interface **before** it has been broadcast.

**Comment by benthecarman** [comment] 2021-07-02 14:57
Closing this as I don't think this is a safe feature to add

**Closed by benthecarman** 2021-07-02 14:57 UTC
